### ISSUE TITLE
Bukkit API support planned?

### ISSUE THREAD

**Issue by treyzania** [McEx/McEx#6]
I realize that due to the wildly different nature of Erlang and Java that it would be rather difficult (Due to needing something like [JInterface](http://erlang.org/doc/apps/jinterface/jinterface_users_guide.html)) and probably plugins would probably run rather poorly.  Though it would be fantastic to be able to support at least _some_ plugins.

I'd make a fork myself, but I don't know Erlang/Elixir.

Thanks!

**Comment by hansihe** [comment]
Development is currently focused on implementing vanilla server features, there is not even an elixir plugin api yet.

Support for bukkit plugins is not planned, and will probably never happen. There are many reasons for this including differing programming models between mcex and bukkit, different programming languages, and limited developer time.
