### ISSUE TITLE
cutkey: exited in: :cutkey_app.start(:normal, [])

### ISSUE THREAD

**Issue by NigelThorne** [McEx/McEx#7]
I'm having trouble starting this server. 
I'm new to elixir and to rust. 
I cloned the repository and installed the tool chain. 

When I get to the last command in your ReadMe... I get the following...
```
~/c/e/mcex> iex -S mix
Erlang/OTP 19 [erts-8.3] [source-d5c06c6] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]


=INFO REPORT==== 14-Apr-2017::20:53:07 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application cutkey: exited in: :cutkey_app.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:open_error, -10}}
            (cutkey) /home/nigel/code/elixir_minecraft_server/mcex/deps/cutkey/src/cutkey_app.erl:33: :cutkey_app.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
```

So as I read this.. it's a cutkey issue getting an open_error (-10).

**Comment by ghost** [comment]
What operating system?

**Comment by NigelThorne** [comment]
ubuntu

```
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial
```

**Comment by ghost** [comment]
Ok, I experience this as well. I suspect that the native driver isn't being built/loaded. I'll look into it and let you know what I find

**Comment by NigelThorne** [comment]
I just sent a pull request (to the mcprotocol project) for removing the dependency on cutkey (as it's not being used)... I've switched to using that and the server starts up. I'm happy to close this as a result.

**Comment by hansihe** [comment]
Keep in mind that this project is far from done, and I haven't worked on it in some time.

You shouldn't really expect to be able to use it for anything useful.
